// Expanded perfume data with 80 items and diverse categories
const perfumes = [
    // Original 24 items (keeping your existing data)
    {
        id: 1,
        name: "Desert Gold",
        brand: "Nubian Essence",
        price: 89.99,
        rating: 4.8,
        gender: "Unisex",
        image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=600",
        description: "A warm, golden fragrance inspired by the Nubian desert at sunset. Notes of amber, sandalwood, and rare spices create an unforgettable aura of luxury.",
        category: "Oriental",
        notes: ["Amber", "Sandalwood", "Spices"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 2,
        name: "Nile Mystique",
        brand: "Royal Nubia",
        price: 120.00,
        rating: 4.9,
        gender: "Women",
        image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600",
        description: "Elegant and mysterious, this fragrance captures the essence of the Nile. Floral notes of lotus and jasmine blend with musk and vanilla.",
        category: "Floral",
        notes: ["Lotus", "Jasmine", "Musk", "Vanilla"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Summer"]
    },
    {
        id: 3,
        name: "Pharaoh's Pride",
        brand: "Ancient Scents",
        price: 150.00,
        rating: 4.7,
        gender: "Men",
        image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600",
        description: "Bold and commanding, this scent embodies the strength of ancient Nubian kings. Leather, oud, and cedarwood create a powerful presence.",
        category: "Woody",
        notes: ["Leather", "Oud", "Cedarwood"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 4,
        name: "Golden Pyramid",
        brand: "Nubian Essence",
        price: 95.00,
        rating: 4.6,
        gender: "Unisex",
        image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=600",
        description: "A harmonious blend of citrus and precious woods, inspired by the golden capstones of Nubian pyramids.",
        category: "Citrus Woody",
        notes: ["Bergamot", "Cedar", "Gold Accord"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 5,
        name: "Queen Amanishakheto",
        brand: "Royal Nubia",
        price: 200.00,
        rating: 5.0,
        gender: "Women",
        image: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=600",
        description: "Named after the great Nubian queen, this luxurious fragrance combines rare rose oils, gold-infused notes, and royal incense.",
        category: "Oriental Floral",
        notes: ["Damask Rose", "Gold", "Incense"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 6,
        name: "Warrior's Spirit",
        brand: "Ancient Scents",
        price: 75.00,
        rating: 4.5,
        gender: "Men",
        image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600",
        description: "Fresh and invigorating, this scent captures the spirit of Nubian warriors. Bergamot, pepper, and vetiver create an energetic profile.",
        category: "Aromatic Spicy",
        notes: ["Bergamot", "Pepper", "Vetiver"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 7,
        name: "Sand Dunes",
        brand: "Desert Rose",
        price: 65.00,
        rating: 4.3,
        gender: "Unisex",
        image: "https://images.unsplash.com/photo-1592914610354-fd354ea45e48?w=600",
        description: "Light and airy, evoking the shifting sands of the Nubian desert. Notes of fig, iris, and white musk.",
        category: "Fresh",
        notes: ["Fig", "Iris", "White Musk"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 8,
        name: "Temple of Amun",
        brand: "Sacred Scents",
        price: 180.00,
        rating: 4.9,
        gender: "Unisex",
        image: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600",
        description: "Spiritual and transcendent, featuring frankincense, myrrh, and sacred woods used in ancient Nubian temples.",
        category: "Oriental",
        notes: ["Frankincense", "Myrrh", "Sacred Woods"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 9,
        name: "Kush Kingdom",
        brand: "Royal Nubia",
        price: 135.00,
        rating: 4.7,
        gender: "Men",
        image: "https://images.unsplash.com/photo-1519669011783-4eaa95fa1b7d?w=600",
        description: "A tribute to the Kingdom of Kush, blending tobacco, rum, and exotic spices for a rich, complex scent.",
        category: "Oriental Woody",
        notes: ["Tobacco", "Rum", "Spices"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 10,
        name: "Nubian Rose",
        brand: "Desert Rose",
        price: 85.00,
        rating: 4.4,
        gender: "Women",
        image: "https://images.unsplash.com/photo-1547887538-047f814bfb64?w=600",
        description: "Delicate yet persistent, featuring Damask rose, saffron, and hints of honey. A true floral masterpiece.",
        category: "Floral Oriental",
        notes: ["Damask Rose", "Saffron", "Honey"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Fall"]
    },
    {
        id: 11,
        name: "Cairo Nights",
        brand: "Ancient Scents",
        price: 110.00,
        rating: 4.6,
        gender: "Unisex",
        image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600",
        description: "Mysterious and seductive, inspired by the vibrant nights of ancient Nubian cities. Oud, rose, and patchouli.",
        category: "Oriental",
        notes: ["Oud", "Rose", "Patchouli"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 12,
        name: "Sun Goddess",
        brand: "Nubian Essence",
        price: 140.00,
        rating: 4.8,
        gender: "Women",
        image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600",
        description: "Radiant and warm, capturing the essence of the Nubian sun. Solar notes, ylang-ylang, and golden amber.",
        category: "Floral Oriental",
        notes: ["Solar Notes", "Ylang-Ylang", "Amber"],
        concentration: "Eau de Parfum",
        season: ["Summer", "Spring"]
    },
    {
        id: 13,
        name: "Desert Mirage",
        brand: "Desert Rose",
        price: 99.00,
        rating: 4.5,
        gender: "Unisex",
        image: "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?w=600",
        description: "An ethereal blend that seems to appear and disappear like a desert mirage. Notes of grapefruit, sage, and sea salt.",
        category: "Fresh Aromatic",
        notes: ["Grapefruit", "Sage", "Sea Salt"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 14,
        name: "Nubian Queen",
        brand: "Royal Nubia",
        price: 250.00,
        rating: 5.0,
        gender: "Women",
        image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600",
        description: "The ultimate expression of feminine royalty. Rare orchid, pearl essence, and liquid gold create an unforgettable signature.",
        category: "Oriental Floral",
        notes: ["Orchid", "Pearl", "Gold"],
        concentration: "Extrait de Parfum",
        season: ["All Seasons"]
    },
    {
        id: 15,
        name: "Sphinx Secret",
        brand: "Ancient Scents",
        price: 165.00,
        rating: 4.8,
        gender: "Men",
        image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600",
        description: "Mysterious and enigmatic like the Sphinx itself. Dark chocolate, tobacco, and ancient woods guard this secret scent.",
        category: "Oriental Gourmand",
        notes: ["Dark Chocolate", "Tobacco", "Woods"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 16,
        name: "Oasis Breeze",
        brand: "Desert Rose",
        price: 70.00,
        rating: 4.2,
        gender: "Unisex",
        image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=600",
        description: "Fresh and revitalizing as an oasis in the desert. Cucumber, mint, and aquatic notes bring instant refreshment.",
        category: "Fresh Aquatic",
        notes: ["Cucumber", "Mint", "Aquatic Notes"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 17,
        name: "Pharaoh's Gold",
        brand: "Royal Nubia",
        price: 300.00,
        rating: 4.9,
        gender: "Men",
        image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600",
        description: "The most precious scent in the collection. Pure gold extract, rare oud, and imperial musk for the modern pharaoh.",
        category: "Oriental Woody",
        notes: ["Gold", "Oud", "Musk"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 18,
        name: "Lotus Dream",
        brand: "Sacred Scents",
        price: 115.00,
        rating: 4.6,
        gender: "Women",
        image: "https://images.unsplash.com/photo-1590736969955-71cc94901144?w=600",
        description: "A dreamy, meditative fragrance centered on the sacred blue lotus. Water lily, white tea, and soft musk.",
        category: "Floral Aquatic",
        notes: ["Blue Lotus", "White Tea", "Musk"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Summer"]
    },
    {
        id: 19,
        name: "Sahara Storm",
        brand: "Nubian Essence",
        price: 130.00,
        rating: 4.7,
        gender: "Men",
        image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600",
        description: "Powerful and untamed like a desert storm. Saffron, pepper, and dry woods create an intense, lasting impression.",
        category: "Spicy Woody",
        notes: ["Saffron", "Pepper", "Dry Woods"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 20,
        name: "Cleopatra's Kiss",
        brand: "Royal Nubia",
        price: 220.00,
        rating: 4.9,
        gender: "Women",
        image: "https://images.unsplash.com/photo-1547887538-047f814bfb64?w=600",
        description: "Seductive and irresistible, this scent captures the legendary allure of Cleopatra. Honey, fig, and precious spices.",
        category: "Oriental Gourmand",
        notes: ["Honey", "Fig", "Spices"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 21,
        name: "Anubis Shadow",
        brand: "Sacred Scents",
        price: 145.00,
        rating: 4.5,
        gender: "Men",
        image: "https://images.unsplash.com/photo-1592914610354-fd354ea45e48?w=600",
        description: "Dark and mysterious, invoking the guardian of the underworld. Black amber, myrrh, and shadowy incense.",
        category: "Oriental",
        notes: ["Black Amber", "Myrrh", "Incense"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 22,
        name: "Papyrus Scroll",
        brand: "Ancient Scents",
        price: 88.00,
        rating: 4.3,
        gender: "Unisex",
        image: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600",
        description: "Dry and intellectual, like ancient papyrus holding secrets of the past. Paper notes, cedar, and vintage ink.",
        category: "Woody Aromatic",
        notes: ["Papyrus", "Cedar", "Ink"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Fall"]
    },
    {
        id: 23,
        name: "Horus Vision",
        brand: "Nubian Essence",
        price: 175.00,
        rating: 4.8,
        gender: "Men",
        image: "https://images.unsplash.com/photo-1519669011783-4eaa95fa1b7d?w=600",
        description: "Clear-sighted and powerful like the falcon god. Juniper, sky accord, and visionary herbs.",
        category: "Aromatic Fresh",
        notes: ["Juniper", "Sky Accord", "Herbs"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Summer"]
    },
    {
        id: 24,
        name: "Isis Blessing",
        brand: "Sacred Scents",
        price: 195.00,
        rating: 4.9,
        gender: "Women",
        image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600",
        description: "Nurturing and magical, blessed by the goddess herself. Mother-of-pearl, moonflower, and protective amber.",
        category: "Oriental Floral",
        notes: ["Moonflower", "Pearl", "Amber"],
        concentration: "Extrait de Parfum",
        season: ["All Seasons"]
    },

    // NEW ADDITIONS 25-40: Floral Collection
    {
        id: 25,
        name: "Midnight Jasmine",
        brand: "Desert Bloom",
        price: 95.00,
        rating: 4.7,
        gender: "Women",
        image: "https://cdn.shopify.com/s/files/1/0047/4067/7699/files/Floral-Jasmine-Floralcy-Tuberose-and-White-Flowers.png?v=1712930129",
        description: "Intoxicating jasmine blossoms under the moonlight. A pure floral experience with hints of green tea and white flowers.",
        category: "Floral",
        notes: ["Jasmine", "Green Tea", "White Flowers"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Summer"]
    },
    {
        id: 26,
        name: "Velvet Rose",
        brand: "Royal Petals",
        price: 125.00,
        rating: 4.8,
        gender: "Women",
        image: "https://thumbs.dreamstime.com/b/pink-elegant-perfume-bottle-rose-fragrance-high-quality-photo-pink-elegant-perfume-bottle-rose-fragrance-352983944.jpg",
        description: "Luxurious Damask rose wrapped in velvet musk. A timeless classic for the modern romantic.",
        category: "Floral Musk",
        notes: ["Damask Rose", "Velvet Musk", "Pink Pepper"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Fall"]
    },
    {
        id: 27,
        name: "Tuberose Twilight",
        brand: "Night Garden",
        price: 140.00,
        rating: 4.6,
        gender: "Women",
        image: "https://zaoud.it/cdn/shop/files/white-as-tuberose-perfume-bottle-surrounded-with-vnilla-and-jasmine-against-white-background.jpg?v=1726076009&width=1445",
        description: "Voluptuous tuberose blooms in the twilight hours. Creamy, intoxicating, and utterly feminine.",
        category: "Floral",
        notes: ["Tuberose", "Vanilla", "Jasmine"],
        concentration: "Extrait de Parfum",
        season: ["Summer", "Fall"]
    },
    {
        id: 28,
        name: "Lavender Fields",
        brand: "Provence Dreams",
        price: 65.00,
        rating: 4.4,
        gender: "Unisex",
        image: "https://static.vecteezy.com/system/resources/previews/058/231/484/large_2x/luxury-perfume-bottle-in-lavender-field-photo.jpeg",
        description: "Calming lavender from the fields of Provence. Aromatic herbs and soft vanilla create a soothing escape.",
        category: "Aromatic",
        notes: ["Lavender", "Herbs", "Vanilla"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 29,
        name: "Ylang Paradise",
        brand: "Tropical Essence",
        price: 85.00,
        rating: 4.5,
        gender: "Women",
        image: "https://thumbs.dreamstime.com/b/perfume-bottle-surrounded-exotic-ylang-flowers-green-tropical-leaves-isolated-white-background-353245020.jpg",
        description: "Exotic ylang-ylang from tropical gardens. Sweet, floral, and irresistibly seductive.",
        category: "Floral Oriental",
        notes: ["Ylang-Ylang", "Coconut", "Vanilla"],
        concentration: "Eau de Parfum",
        season: ["Summer"]
    },
    {
        id: 30,
        name: "Neroli Sunrise",
        brand: "Citrus Grove",
        price: 78.00,
        rating: 4.6,
        gender: "Unisex",
        image: "https://cdn.shopify.com/s/files/1/0250/8482/1600/files/bergamotto-di-positano.jpg?v=1721053393",
        description: "Bright neroli blossoms at dawn. Fresh, citrusy, and full of Mediterranean sunshine.",
        category: "Citrus Floral",
        notes: ["Neroli", "Bergamot", "Orange Blossom"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 31,
        name: "Gardenia Pearl",
        brand: "White Flowers",
        price: 155.00,
        rating: 4.8,
        gender: "Women",
        image: "https://thumbs.dreamstime.com/b/pink-perfume-bottle-splashing-water-flowers-pink-background-creating-refreshing-elegant-image-pink-perfume-375670695.jpg",
        description: "Luxurious gardenia petals wrapped in pearl musk. Creamy, rich, and sophisticated.",
        category: "White Floral",
        notes: ["Gardenia", "Pearl", "Musk"],
        concentration: "Extrait de Parfum",
        season: ["Spring", "Summer"]
    },
    {
        id: 32,
        name: "Peony Blush",
        brand: "Spring Bloom",
        price: 92.00,
        rating: 4.5,
        gender: "Women",
        image: "https://www.shutterstock.com/image-photo/elegant-perfume-bottle-pink-lily-260nw-2685755373.jpg",
        description: "Soft peony petals with a blush of pink. Delicate, romantic, and fresh.",
        category: "Floral",
        notes: ["Peony", "Pink Pepper", "Rose"],
        concentration: "Eau de Parfum",
        season: ["Spring"]
    },
    {
        id: 33,
        name: "Orange Blossom Honey",
        brand: "Mediterranean",
        price: 88.00,
        rating: 4.7,
        gender: "Women",
        image: "https://static.vecteezy.com/system/resources/previews/058/231/548/large_2x/elegant-pink-perfume-bottle-roses-light-photo.jpeg",
        description: "Sweet orange blossom nectar collected by bees. Gourmand floral at its finest.",
        category: "Floral Gourmand",
        notes: ["Orange Blossom", "Honey", "Almond"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Summer"]
    },
    {
        id: 34,
        name: "Lily of the Valley",
        brand: "Forest Dew",
        price: 72.00,
        rating: 4.3,
        gender: "Women",
        image: "https://i.etsystatic.com/24021474/r/il/6cc768/7180085439/il_570xN.7180085439_pbux.jpg",
        description: "Delicate lily of the valley in morning dew. Fresh, green, and pure.",
        category: "Green Floral",
        notes: ["Lily of the Valley", "Green Leaves", "Musk"],
        concentration: "Eau de Toilette",
        season: ["Spring"]
    },
    {
        id: 35,
        name: "Magnolia Grandiflora",
        brand: "Southern Belle",
        price: 110.00,
        rating: 4.6,
        gender: "Women",
        image: "https://www.cleanbeauty.com/cdn/shop/files/CBC_February2023_Digital_Reserve_CItronFig_01_SQUARE.webp?v=1770308056&width=1500",
        description: "Grand magnolia blossoms from the Deep South. Creamy, lemony, and utterly elegant.",
        category: "White Floral",
        notes: ["Magnolia", "Lemon", "Cream"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Summer"]
    },
    {
        id: 36,
        name: "Cherry Blossom",
        brand: "Sakura Dreams",
        price: 68.00,
        rating: 4.4,
        gender: "Women",
        image: "https://img.shopstyle-cdn.com/sim/14/40/1440659181d113a8d45f55af58008a41_best/2pcs-combo-orientica-arte-bellissimo-exotic-by-orientica-eau-de-parfum-spray-2-5-oz-women.jpg",
        description: "Delicate cherry blossoms in spring. Ethereal, powdery, and fleetingly beautiful.",
        category: "Floral",
        notes: ["Cherry Blossom", "Rice Powder", "Musk"],
        concentration: "Eau de Toilette",
        season: ["Spring"]
    },
    {
        id: 37,
        name: "Iris Pallida",
        brand: "Purple Harvest",
        price: 165.00,
        rating: 4.8,
        gender: "Unisex",
        image: "https://thumbs.dreamstime.com/b/green-perfume-bottle-nestled-lush-moss-ferns-forest-floor-transparent-square-features-blank-label-black-cap-396582749.jpg",
        description: "Rare iris pallida root extract. Powdery, violet, and sophisticated.",
        category: "Powdery Floral",
        notes: ["Iris", "Violet", "Powder"],
        concentration: "Extrait de Parfum",
        season: ["Spring", "Fall"]
    },
    {
        id: 38,
        name: "Frangipani Sunset",
        brand: "Island Dreams",
        price: 79.00,
        rating: 4.5,
        gender: "Women",
        image: "https://static.vecteezy.com/system/resources/previews/067/964/761/non_2x/green-perfume-bottle-with-fresh-mint-leaves-for-natural-fragrance-and-aromatherapy-photo.jpg",
        description: "Tropical frangipani at sunset. Sweet, creamy, and vacation-worthy.",
        category: "Tropical Floral",
        notes: ["Frangipani", "Coconut", "Vanilla"],
        concentration: "Eau de Toilette",
        season: ["Summer"]
    },
    {
        id: 39,
        name: "Violet Leaf",
        brand: "Green Valley",
        price: 82.00,
        rating: 4.4,
        gender: "Unisex",
        image: "https://magnifissance.com/wp-content/uploads/2022/08/Oud-perfume-2.jpg",
        description: "Fresh violet leaves after spring rain. Green, earthy, and natural.",
        category: "Green",
        notes: ["Violet Leaf", "Grass", "Earth"],
        concentration: "Eau de Toilette",
        season: ["Spring"]
    },
    {
        id: 40,
        name: "Rose de Mai",
        brand: "Grasse Atelier",
        price: 185.00,
        rating: 4.9,
        gender: "Women",
        image: "https://thumbs.dreamstime.com/b/perfume-bottle-surrounded-exotic-ylang-flowers-green-tropical-leaves-isolated-white-background-353245020.jpg",
        description: "The finest rose de mai from Grasse. Rich, honeyed, and deeply romantic.",
        category: "Floral",
        notes: ["Rose de Mai", "Honey", "Wine"],
        concentration: "Extrait de Parfum",
        season: ["Spring", "Summer"]
    },

    // NEW ADDITIONS 41-56: Woody & Oriental Collection
    {
        id: 41,
        name: "Sandalwood Temple",
        brand: "Sacred Woods",
        price: 145.00,
        rating: 4.8,
        gender: "Unisex",
        image: "https://eternalperfumeoils.com/cdn/shop/files/Sandalwood_Dream_perfume_oil_bottle_picture.webp?v=1755251729&width=1445",
        description: "Mysore sandalwood from ancient temples. Creamy, spiritual, and meditative.",
        category: "Woody",
        notes: ["Sandalwood", "Incense", "Cream"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 42,
        name: "Cedar Atlas",
        brand: "Mountain Reserve",
        price: 98.00,
        rating: 4.6,
        gender: "Men",
        image: "https://cdn11.bigcommerce.com/s-9a4y5/images/stencil/1280x1280/products/119/789/fougere-100-ml-parfum__53590.1536705350.jpg?c=2",
        description: "Atlas cedar from the Moroccan mountains. Dry, woody, and masculine.",
        category: "Woody",
        notes: ["Cedar", "Vetiver", "Pine"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 43,
        name: "Oud Imperial",
        brand: "Arabian Nights",
        price: 280.00,
        rating: 4.9,
        gender: "Men",
        image: "https://i.ebayimg.com/images/g/4HAAAOSwmGVmWMB8/s-l1200.jpg",
        description: "Aged oud wood from Southeast Asia. Rich, complex, and regal.",
        category: "Oriental Woody",
        notes: ["Oud", "Saffron", "Amber"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 44,
        name: "Vetiver Roots",
        brand: "Earth Collection",
        price: 115.00,
        rating: 4.7,
        gender: "Men",
        image: "https://creedboutique.com/cdn/shop/files/1500x1500_Original-Velvet-Notes.jpg?v=1764096405&width=750",
        description: "Haitian vetiver roots dried in the sun. Earthy, smoky, and grounding.",
        category: "Woody Earthy",
        notes: ["Vetiver", "Earth", "Smoke"],
        concentration: "Eau de Parfum",
        season: ["All Seasons"]
    },
    {
        id: 45,
        name: "Patchouli Noir",
        brand: "Dark Earth",
        price: 105.00,
        rating: 4.5,
        gender: "Unisex",
        image: "https://i.etsystatic.com/13701379/r/il/d5cb0d/6558424898/il_1080xN.6558424898_cfzb.jpg",
        description: "Dark patchouli aged in oak barrels. Mysterious, earthy, and sensual.",
        category: "Oriental Woody",
        notes: ["Patchouli", "Oak", "Dark Chocolate"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 46,
        name: "Amber Resin",
        brand: "Golden Hour",
        price: 135.00,
        rating: 4.8,
        gender: "Unisex",
        image: "https://chairish-prod.freetls.fastly.net/image/product/sized/7fb00c0c-2788-4819-995b-ae008a40d249/saks-fifth-avenue-crystal-gold-amber-perfume-bottle-textured-glass-murano-3550?aspect=fit&width=640&height=640",
        description: "Fossilized amber resin. Warm, sweet, and ancient.",
        category: "Oriental",
        notes: ["Amber", "Vanilla", "Benzoin"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 47,
        name: "Incense Ceremony",
        brand: "Sacred Smoke",
        price: 155.00,
        rating: 4.7,
        gender: "Unisex",
        image: "https://mediafiles.maxaroma.com/9cd29e92-4b8f-436f-ad1f-8e368b30dc1d/https://www.maxaroma.com/productimages/large/UP679602480680_2.jpg?ver=1758754704",
        description: "Japanese temple incense. Spiritual, smoky, and transcendent.",
        category: "Oriental",
        notes: ["Incense", "Cedar", "Spices"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 48,
        name: "Leather Bound",
        brand: "Library Collection",
        price: 175.00,
        rating: 4.6,
        gender: "Men",
        image: "https://cdn11.bigcommerce.com/s-9a4y5/images/stencil/1280x1280/products/311/1038/DCB658E2-338F-40E8-B9B5-8E49083593F9__64917.1587081690.jpg?c=2",
        description: "Fine leather book bindings. Rich, sophisticated, and intellectual.",
        category: "Leather",
        notes: ["Leather", "Paper", "Vanilla"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 49,
        name: "Tobacco Vanille",
        brand: "Gentleman's Club",
        price: 165.00,
        rating: 4.8,
        gender: "Men",
        image: "https://www.pairfum.com/wp-content/uploads/2021/01/Chypre-Coty-400x400.jpg",
        description: "Cuban tobacco and Madagascar vanilla. Rich, sweet, and addictive.",
        category: "Oriental Gourmand",
        notes: ["Tobacco", "Vanilla", "Cacao"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 50,
        name: "Myrrh Mystery",
        brand: "Ancient Resins",
        price: 142.00,
        rating: 4.5,
        gender: "Unisex",
        image: "https://di2ponv0v5otw.cloudfront.net/posts/2025/10/27/68ffc907e15c910b3596f61b/m_68ffc90bed788d12ee361f33.jpeg",
        description: "Sacred myrrh from the Horn of Africa. Medicinal, sweet, and mystical.",
        category: "Oriental",
        notes: ["Myrrh", "Opoponax", "Licorice"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 51,
        name: "Saffron Gold",
        brand: "Spice Route",
        price: 195.00,
        rating: 4.7,
        gender: "Unisex",
        image: "https://d2j6dbq0eux0bg.cloudfront.net/images/19881095/4708133976.jpg",
        description: "Iranian saffron threads. Precious, spicy, and luxurious.",
        category: "Oriental Spicy",
        notes: ["Saffron", "Rose", "Amber"],
        concentration: "Extrait de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 52,
        name: "Ebony Wood",
        brand: "Dark Forest",
        price: 125.00,
        rating: 4.6,
        gender: "Men",
        image: "https://kaneen.com/media/catalog/product//P/r/Private-Collection-E-Green-Fougere-Perfume-by-Clive-Christian-Parfum-For-Women-50-ml-3-7fb6459e.webp",
        description: "Rare ebony wood. Dark, dense, and powerful.",
        category: "Woody",
        notes: ["Ebony", "Leather", "Smoke"],
        concentration: "Eau de Parfum",
        season: ["Winter"]
    },
    {
        id: 53,
        name: "Benzoin Balsam",
        brand: "Resin Collection",
        price: 108.00,
        rating: 4.4,
        gender: "Unisex",
        image: "https://paradyseperfumes.com/cdn/shop/files/whjite.png?v=1745573707&width=1200",
        description: "Sweet benzoin resin from Sumatra. Vanilla-like, comforting, and warm.",
        category: "Oriental",
        notes: ["Benzoin", "Vanilla", "Cinnamon"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 54,
        name: "Cypriol Earth",
        brand: "Indian Summer",
        price: 118.00,
        rating: 4.5,
        gender: "Men",
        image: "https://cdn.zeptonow.com/production/ik-seo/tr:w-640,ar-2400-2400,pr-true,f-auto,q-80/cms/product_variant/c6852675-e606-4d62-be45-027209a2be1c/Villain-Hydra-Perfume-100-Ml-Eau-De-Parfum-Premium-Long-Lasting-Fragrance-Spray-Aquatic.jpeg",
        description: "Indian cypriol root. Earthy, spicy, and exotic.",
        category: "Woody Spicy",
        notes: ["Cypriol", "Patchouli", "Spices"],
        concentration: "Eau de Parfum",
        season: ["Fall"]
    },
    {
        id: 55,
        name: "Guaiac Wood",
        brand: "Smoke & Wood",
        price: 132.00,
        rating: 4.6,
        gender: "Unisex",
        image: "https://media.neimanmarcus.com/f_auto,q_auto:low,ar_4:5,c_fill,dpr_2.0,w_790/01/nm_5061668_100000_m",
        description: "Smoky guaiac wood. Tar-like, rose-like, and mysterious.",
        category: "Woody",
        notes: ["Guaiac Wood", "Rose", "Smoke"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 56,
        name: "Agarwood Smoke",
        brand: "Mystic East",
        price: 265.00,
        rating: 4.9,
        gender: "Men",
        image: "https://breathefragrances.com/wp-content/uploads/2024/05/so-clean-white-musk-scaled.jpg",
        description: "Smoky agarwood from Assam. Complex, medicinal, and precious.",
        category: "Oriental Woody",
        notes: ["Agarwood", "Smoke", "Incense"],
        concentration: "Extrait de Parfum",
        season: ["Winter"]
    },

    // NEW ADDITIONS 57-72: Fresh & Citrus Collection
    {
        id: 57,
        name: "Bergamot Zest",
        brand: "Italian Citrus",
        price: 75.00,
        rating: 4.6,
        gender: "Unisex",
        image: "https://cdn.shopify.com/s/files/1/0250/8482/1600/files/bergamotto-di-positano.jpg?v=1721053393",
        description: "Calabrian bergamot freshly squeezed. Bright, zesty, and uplifting.",
        category: "Citrus",
        notes: ["Bergamot", "Lemon", "Petitgrain"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 58,
        name: "Mediterranean Breeze",
        brand: "Coastal Living",
        price: 68.00,
        rating: 4.5,
        gender: "Unisex",
        image: "https://cdn.zeptonow.com/production/ik-seo/tr:w-640,ar-2400-2400,pr-true,f-auto,q-80/cms/product_variant/c6852675-e606-4d62-be45-027209a2be1c/Villain-Hydra-Perfume-100-Ml-Eau-De-Parfum-Premium-Long-Lasting-Fragrance-Spray-Aquatic.jpeg",
        description: "Sea breeze along the Amalfi coast. Fresh, aquatic, and invigorating.",
        category: "Aquatic",
        notes: ["Sea Salt", "Citrus", "Seaweed"],
        concentration: "Eau de Toilette",
        season: ["Summer"]
    },
    {
        id: 59,
        name: "Green Tea Ceremony",
        brand: "Zen Garden",
        price: 82.00,
        rating: 4.4,
        gender: "Unisex",
        image: "https://thumbs.dreamstime.com/b/green-perfume-bottle-nestled-lush-moss-ferns-forest-floor-transparent-square-features-blank-label-black-cap-396582749.jpg",
        description: "Japanese matcha green tea. Fresh, grassy, and calming.",
        category: "Green",
        notes: ["Green Tea", "Matcha", "Bamboo"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 60,
        name: "Lemon Grove",
        brand: "Sicilian Sun",
        price: 65.00,
        rating: 4.3,
        gender: "Unisex",
        image: "https://static.vecteezy.com/system/resources/previews/067/964/761/non_2x/green-perfume-bottle-with-fresh-mint-leaves-for-natural-fragrance-and-aromatherapy-photo.jpg",
        description: "Sicilian lemon trees in full sun. Zesty, bright, and cheerful.",
        category: "Citrus",
        notes: ["Lemon", "Sicilian Lemon", "Verbena"],
        concentration: "Eau de Cologne",
        season: ["Spring", "Summer"]
    },
    {
        id: 61,
        name: "Ocean Mist",
        brand: "Marine Life",
        price: 78.00,
        rating: 4.5,
        gender: "Men",
        image: "https://cdn.zeptonow.com/production/ik-seo/tr:w-640,ar-2400-2400,pr-true,f-auto,q-80/cms/product_variant/c6852675-e606-4d62-be45-027209a2be1c/Villain-Hydra-Perfume-100-Ml-Eau-De-Parfum-Premium-Long-Lasting-Fragrance-Spray-Aquatic.jpeg",
        description: "Morning mist over the Atlantic. Fresh, watery, and clean.",
        category: "Aquatic",
        notes: ["Water Notes", "Cucumber", "Melon"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 62,
        name: "Grapefruit Spark",
        brand: "Citrus Burst",
        price: 72.00,
        rating: 4.4,
        gender: "Women",
        image: "https://www.cleanbeauty.com/cdn/shop/files/CBC_February2023_Digital_Reserve_CItronFig_01_SQUARE.webp?v=1770308056&width=1500",
        description: "Pink grapefruit with a sparkling twist. Juicy, vibrant, and energizing.",
        category: "Citrus",
        notes: ["Grapefruit", "Pink Pepper", "Musk"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 63,
        name: "Bamboo Forest",
        brand: "Asian Gardens",
        price: 88.00,
        rating: 4.6,
        gender: "Unisex",
        image: "https://thumbs.dreamstime.com/b/green-perfume-bottle-nestled-lush-moss-ferns-forest-floor-transparent-square-features-blank-label-black-cap-396582749.jpg",
        description: "Fresh bamboo after spring rain. Green, watery, and serene.",
        category: "Green Aquatic",
        notes: ["Bamboo", "Water", "Green Notes"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 64,
        name: "Verbena Fields",
        brand: "Provence Herbs",
        price: 62.00,
        rating: 4.3,
        gender: "Unisex",
        image: "https://static.vecteezy.com/system/resources/previews/058/231/484/large_2x/luxury-perfume-bottle-in-lavender-field-photo.jpeg",
        description: "Lemon verbena from Provence gardens. Citrusy, herbal, and refreshing.",
        category: "Aromatic Citrus",
        notes: ["Verbena", "Lemon", "Herbs"],
        concentration: "Eau de Cologne",
        season: ["Spring", "Summer"]
    },
    {
        id: 65,
        name: "Rain Water",
        brand: "Fresh Drops",
        price: 58.00,
        rating: 4.2,
        gender: "Unisex",
        image: "https://thumbs.dreamstime.com/b/pink-perfume-bottle-splashing-water-flowers-pink-background-creating-refreshing-elegant-image-pink-perfume-375670695.jpg",
        description: "Petrichor after summer rain. Mineral, fresh, and clean.",
        category: "Aquatic",
        notes: ["Rain", "Petrichor", "Minerals"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 66,
        name: "Mint Leaf",
        brand: "Herbal Garden",
        price: 55.00,
        rating: 4.1,
        gender: "Unisex",
        image: "https://static.vecteezy.com/system/resources/previews/067/964/761/non_2x/green-perfume-bottle-with-fresh-mint-leaves-for-natural-fragrance-and-aromatherapy-photo.jpg",
        description: "Fresh peppermint leaves. Cool, refreshing, and invigorating.",
        category: "Aromatic",
        notes: ["Peppermint", "Spearmint", "Citrus"],
        concentration: "Eau de Cologne",
        season: ["Spring", "Summer"]
    },
    {
        id: 67,
        name: "Cucumber Water",
        brand: "Spa Collection",
        price: 68.00,
        rating: 4.4,
        gender: "Women",
        image: "https://www.shutterstock.com/image-photo/elegant-perfume-bottle-pink-lily-260nw-2685755373.jpg",
        description: "Cool cucumber spa water. Fresh, watery, and calming.",
        category: "Fresh Aquatic",
        notes: ["Cucumber", "Water", "Aloe"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 68,
        name: "Lime Basil",
        brand: "Kitchen Garden",
        price: 74.00,
        rating: 4.5,
        gender: "Unisex",
        image: "https://i.etsystatic.com/24021474/r/il/6cc768/7180085439/il_570xN.7180085439_pbux.jpg",
        description: "Mexican lime and fresh basil. Zesty, herbal, and gourmet.",
        category: "Citrus Aromatic",
        notes: ["Lime", "Basil", "Thyme"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 69,
        name: "White Linen",
        brand: "Clean Laundry",
        price: 60.00,
        rating: 4.3,
        gender: "Women",
        image: "https://breathefragrances.com/wp-content/uploads/2024/05/so-clean-white-musk-scaled.jpg",
        description: "Freshly laundered white sheets. Clean, cotton, and comforting.",
        category: "Fresh",
        notes: ["Cotton", "Linen", "White Musk"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 70,
        name: "Sea Breeze",
        brand: "Coastal Walk",
        price: 76.00,
        rating: 4.5,
        gender: "Unisex",
        image: "https://cdn.zeptonow.com/production/ik-seo/tr:w-640,ar-2400-2400,pr-true,f-auto,q-80/cms/product_variant/c6852675-e606-4d62-be45-027209a2be1c/Villain-Hydra-Perfume-100-Ml-Eau-De-Parfum-Premium-Long-Lasting-Fragrance-Spray-Aquatic.jpeg",
        description: "Wind from the ocean. Salty, fresh, and free.",
        category: "Aquatic",
        notes: ["Sea Salt", "Wind", "Driftwood"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    },
    {
        id: 71,
        name: "Eucalyptus Mist",
        brand: "Australian Bush",
        price: 70.00,
        rating: 4.4,
        gender: "Unisex",
        image: "https://thumbs.dreamstime.com/b/green-perfume-bottle-nestled-lush-moss-ferns-forest-floor-transparent-square-features-blank-label-black-cap-396582749.jpg",
        description: "Australian eucalyptus after rain. Medicinal, fresh, and clearing.",
        category: "Aromatic",
        notes: ["Eucalyptus", "Mint", "Camphor"],
        concentration: "Eau de Toilette",
        season: ["All Seasons"]
    },
    {
        id: 72,
        name: "Citrus Grove",
        brand: "Orchard Fresh",
        price: 66.00,
        rating: 4.3,
        gender: "Unisex",
        image: "https://cdn.shopify.com/s/files/1/0250/8482/1600/files/bergamotto-di-positano.jpg?v=1721053393",
        description: "Mixed citrus orchard. Orange, lemon, and lime in harmony.",
        category: "Citrus",
        notes: ["Orange", "Lemon", "Lime"],
        concentration: "Eau de Cologne",
        season: ["Spring", "Summer"]
    },

    // NEW ADDITIONS 73-80: Gourmand & Special Collection
    {
        id: 73,
        name: "Vanilla Bourbon",
        brand: "Sweet Indulgence",
        price: 95.00,
        rating: 4.7,
        gender: "Women",
        image: "https://www.gourmandbeauty.com/cdn/shop/files/le-monde-gourmand-shopify-pdp-gallery-eau-de-parfum-jumbo-creme-vanille-jumbo-stylized-still-life-image-desktop-1540x1824_99662ba3-c30e-4e73-9316-1fe03a716bd7.jpg?v=1770395000&width=1500",
        description: "Madagascar vanilla aged in bourbon barrels. Sweet, rich, and intoxicating.",
        category: "Gourmand",
        notes: ["Vanilla", "Bourbon", "Caramel"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 74,
        name: "Chocolate Decadence",
        brand: "Cocoa Dreams",
        price: 88.00,
        rating: 4.6,
        gender: "Women",
        image: "https://theduabrand.com/cdn/shop/files/front_Liquor_Chocolates_Vanilla_1024x1024.jpg?v=1728397822",
        description: "Dark Belgian chocolate. Rich, creamy, and sinful.",
        category: "Gourmand",
        notes: ["Dark Chocolate", "Cacao", "Vanilla"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 75,
        name: "Caramel Drizzle",
        brand: "Sweet Shop",
        price: 78.00,
        rating: 4.5,
        gender: "Women",
        image: "http://theduabrand.com/cdn/shop/files/front_Dark_Chocolate_Rum_and_Vanilla_2nd.webp?v=1751379920",
        description: "Salted caramel sauce. Sweet, buttery, and addictive.",
        category: "Gourmand",
        notes: ["Caramel", "Salt", "Butter"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 76,
        name: "Coffee Roast",
        brand: "Morning Brew",
        price: 85.00,
        rating: 4.6,
        gender: "Unisex",
        image: "https://cdn.shopify.com/s/files/1/0554/9382/0450/files/Fresh_Spicy_Fragrance.jpg?v=1738939288",
        description: "Freshly roasted coffee beans. Bitter, rich, and energizing.",
        category: "Gourmand",
        notes: ["Coffee", "Cacao", "Vanilla"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 77,
        name: "Honey Elixir",
        brand: "Bee Garden",
        price: 92.00,
        rating: 4.5,
        gender: "Women",
        image: "https://fernwehcollective.com/cdn/shop/articles/Saffron_in_Fernweh_Perfume.webp?crop=center&height=940&v=1753359715&width=940",
        description: "Wildflower honey from alpine meadows. Sweet, floral, and golden.",
        category: "Gourmand Floral",
        notes: ["Honey", "Beeswax", "Floral"],
        concentration: "Eau de Parfum",
        season: ["Spring", "Fall"]
    },
    {
        id: 78,
        name: "Almond Biscuit",
        brand: "Patisserie",
        price: 80.00,
        rating: 4.4,
        gender: "Women",
        image: "https://zaoud.it/cdn/shop/files/white-as-tuberose-perfume-bottle-beside-box-against-white-background.jpg?v=1726076009&width=1445",
        description: "French almond macarons. Nutty, sweet, and delicate.",
        category: "Gourmand",
        notes: ["Almond", "Vanilla", "Sugar"],
        concentration: "Eau de Toilette",
        season: ["All Seasons"]
    },
    {
        id: 79,
        name: "Spiced Rum",
        brand: "Caribbean Nights",
        price: 105.00,
        rating: 4.7,
        gender: "Men",
        image: "https://img.shopstyle-cdn.com/sim/14/40/1440659181d113a8d45f55af58008a41_best/2pcs-combo-orientica-arte-bellissimo-exotic-by-orientica-eau-de-parfum-spray-2-5-oz-women.jpg",
        description: "Aged Caribbean rum with spices. Warm, sweet, and intoxicating.",
        category: "Oriental Gourmand",
        notes: ["Rum", "Cinnamon", "Vanilla"],
        concentration: "Eau de Parfum",
        season: ["Fall", "Winter"]
    },
    {
        id: 80,
        name: "Cotton Candy",
        brand: "Carnival Treats",
        price: 55.00,
        rating: 4.2,
        gender: "Women",
        image: "https://thumbs.dreamstime.com/b/pink-perfume-bottle-splashing-water-flowers-pink-background-creating-refreshing-elegant-image-pink-perfume-375670695.jpg",
        description: "Sweet cotton candy at the fair. Sugary, playful, and nostalgic.",
        category: "Gourmand",
        notes: ["Sugar", "Strawberry", "Vanilla"],
        concentration: "Eau de Toilette",
        season: ["Spring", "Summer"]
    }
];

// Enhanced filters configuration
const filters = {
    gender: ["Men", "Women", "Unisex"],
    category: [
        "Floral", "Oriental", "Woody", "Fresh", "Citrus", 
        "Gourmand", "Aquatic", "Aromatic", "Leather", "Green",
        "Oriental Floral", "Oriental Woody", "Floral Oriental",
        "White Floral", "Woody Spicy", "Citrus Floral", "Fresh Aquatic"
    ],
    priceRange: [
        { label: "Under $50", min: 0, max: 50 },
        { label: "$50 - $100", min: 50, max: 100 },
        { label: "$100 - $150", min: 100, max: 150 },
        { label: "$150 - $200", min: 150, max: 200 },
        { label: "Over $200", min: 200, max: Infinity }
    ],
    concentration: ["Eau de Cologne", "Eau de Toilette", "Eau de Parfum", "Extrait de Parfum"],
    season: ["Spring", "Summer", "Fall", "Winter", "All Seasons"],
    rating: [4.0, 4.5, 4.8, 5.0]
};

// Promo codes (keeping your existing codes)
const promoCodes = {
    'NUBIAN10': 0.10,
    'GNOUBY20': 0.20,
    'WELCOME15': 0.15,
    'GOLD25': 0.25,
    'GANOUBY30': 0.30,
    'FLORAL15': 0.15,
    'WOODY20': 0.20,
    'FRESH10': 0.10,
    'GOURMAND25': 0.25,
    'LUXURY30': 0.30
};

// Helper functions for filtering
const filterFunctions = {
    byGender: (perfumes, gender) => perfumes.filter(p => p.gender === gender || p.gender === "Unisex"),
    byCategory: (perfumes, category) => perfumes.filter(p => p.category === category || p.category.includes(category)),
    byPriceRange: (perfumes, min, max) => perfumes.filter(p => p.price >= min && p.price <= max),
    byConcentration: (perfumes, concentration) => perfumes.filter(p => p.concentration === concentration),
    bySeason: (perfumes, season) => perfumes.filter(p => p.season.includes(season) || p.season.includes("All Seasons")),
    byRating: (perfumes, minRating) => perfumes.filter(p => p.rating >= minRating),
    byNote: (perfumes, note) => perfumes.filter(p => p.notes.some(n => n.toLowerCase().includes(note.toLowerCase())))
};

// Export for use in your application
// module.exports = { perfumes, filters, promoCodes, filterFunctions };